name = "Minimalist - Valde.ci"
license = "Apache License 2.0"
licenselink = "https://raw.githubusercontent.com/coderade/coderade-minimalist-theme/master/LICENSE.md"
description = "A minimalistic theme with the focus on blogging."
homepage = "https://github.com/digitalcraftsman"
tags = ["disqus", "google analytics", "responsive", "syntax highlighting", "l10n"]
features = []
min_version = 0.20

[author]
  name = "Valdeci Gomes" 
  homepage = "https://valde.ci"


